add_subdirectory(aggregation)
add_subdirectory(database)
add_subdirectory(detailfetchrequest)
add_subdirectory(displaylabelgroups)
add_subdirectory(memorytable)
add_subdirectory(phonenumber)
add_subdirectory(qcontactmanager)
add_subdirectory(qcontactmanagerfiltering)
add_subdirectory(synctransactions)
